# Generated by Django 6.0.1 on 2026-01-13 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_estacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacion',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='estacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='inventory.estacion'),
            preserve_default=False,
        ),
    ]
