# Generated by Django 6.0.1 on 2026-01-15 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_ubicacion_descripcion_ubicacion_estacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimiento',
            old_name='fecha_hora',
            new_name='fecha',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('TRASLADO', 'Traslado'), ('MANTENIMIENTO', 'Mantenimiento'), ('ALTA', 'Alta'), ('BAJA', 'Baja')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
