# Generated by Django 6.0.1 on 2026-03-05 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_fecha_hora_movimiento_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='ubicacion_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_destino', to='inventory.ubicacion'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='ubicacion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_origen', to='inventory.ubicacion'),
        ),
    ]
