# Generated by Django 6.0.1 on 2026-04-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_movimiento_ubicacion_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='motivo',
            field=models.CharField(blank=True, help_text='Razón breve del movimiento', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activo',
            name='estado',
            field=models.CharField(choices=[('OPERATIVO', 'Operativo'), ('DISPONIBLE', 'Disponible'), ('TRASLADO', 'Traslado'), ('AVERIADO', 'Averiado'), ('REPARACIÓN', 'Reparación'), ('CALIBRACIÓN', 'Calibración'), ('BAJA', 'Baja')], default='DISPONIBLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('OPERATIVO', 'Operativo'), ('DISPONIBLE', 'Disponible'), ('TRASLADO', 'Traslado'), ('AVERIADO', 'Averiado'), ('REPARACIÓN', 'Reparación'), ('CALIBRACIÓN', 'Calibración'), ('BAJA', 'Baja')], default='TRASLADO', max_length=20),
        ),
    ]
