# Generated by Django 6.0.1 on 2026-04-04 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_movimiento_motivo_alter_activo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='inventory.ubicacion'),
        ),
    ]
