# Generated by Django 6.0.1 on 2026-04-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_activo_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='certificado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='activos/certificados/'),
        ),
        migrations.AddField(
            model_name='activo',
            name='fecha_calibracion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activo',
            name='fecha_proxima_verificacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='activos/fotos/'),
        ),
        migrations.AddField(
            model_name='activo',
            name='requiere_calibracion',
            field=models.BooleanField(default=False),
        ),
    ]
