# Generated by Django 6.0.1 on 2026-05-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_activo_certificado_pdf_activo_fecha_calibracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='qr_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='activos/qrs/'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='codigo_qr',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
