# Generated by Django 6.0.1 on 2026-05-25 10:15

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_activo_qr_imagen_alter_activo_codigo_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='codigo_qr',
            field=models.CharField(blank=True, default=inventory.models.generar_codigo_uuid_temporal, max_length=255, unique=True),
        ),
    ]
